### ISSUE TITLE
Testing Application

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/YGOPro-Database#1]
Need a new application to do the following
- Take two parameters, `card.cdb` name, folder name.
- Search folder for `*.sql` files, create a database (can be in memory) and run the SQL commands on them.
- Count the number of cards in each database.
- Output a list of missing card names to `stdout` if under 20, else print to error file.
- If no missing cards return code 1
- If SQL folder contains greater than or equal cards return 0, output DB to file named that of folder.

**Comment by adrianojn** [comment]
https://github.com/adrianojn/checkdb/releases/

**Comment by Zayelion** [comment]
Highly appreciated!
